[package]
name = "rssbot"
version = "1.0.0"
authors = ["iovxw <iovxw@outlook.com>"]
license = "Unlicense"
readme = "README.md"
homepage = "https://github.com/iovxw/rssbot"
repository = "https://github.com/iovxw/rssbot"

[dependencies]
log = "0.3"
env_logger = "0.3"
lazy_static = "0.2"
regex = "1.5"
pinyin-order = "0.1"

quick-xml = "0.7"
error-chain = "*"

telebot = { path = "./telebot" }
# version specified by telebot
serde = "*"
serde_derive = "*"
serde_json = "*"
curl = "*"
futures = "*"
tokio-core = "*"
tokio-curl = "*"
